In [1]:
import pandas as pd
df = pd.read_csv('penguins_size.csv').dropna()
numeric_columns = ['culmen_length_mm','culmen_depth_mm','flipper_length_mm','body_mass_g']
df[numeric_columns]

     culmen_length_mm  culmen_depth_mm  flipper_length_mm  body_mass_g
0                39.1             18.7              181.0       3750.0
1                39.5             17.4              186.0       3800.0
2                40.3             18.0              195.0       3250.0
4                36.7             19.3              193.0       3450.0
5                39.3             20.6              190.0       3650.0
..                ...              ...                ...          ...
338              47.2             13.7              214.0       4925.0
340              46.8             14.3              215.0       4850.0
341              50.4             15.7              222.0       5750.0
342              45.2             14.8              212.0       5200.0
343              49.9             16.1              213.0       5400.0

[334 rows x 4 columns]

We can compute the z-score manually by computing the mean and the standard deviation. `ddof=1` applies Bessel's corrrection, although it is often unnecessary if the number of observations is large.

In [3]:
df[numeric_columns].mean()

culmen_length_mm       43.994311
culmen_depth_mm        17.160479
flipper_length_mm     201.014970
body_mass_g          4209.056886
dtype: float64

In [4]:
df[numeric_columns].std(ddof=1)

culmen_length_mm       5.460521
culmen_depth_mm        1.967909
flipper_length_mm     14.022175
body_mass_g          804.836129
dtype: float64

In [5]:
(df[numeric_columns] - df[numeric_columns].mean())/df[numeric_columns].std(ddof=1)

     culmen_length_mm  culmen_depth_mm  flipper_length_mm  body_mass_g
0           -0.896308         0.782313          -1.427380    -0.570373
1           -0.823055         0.121713          -1.070802    -0.508249
2           -0.676549         0.426605          -0.428961    -1.191618
4           -1.335827         1.087205          -0.571592    -0.943120
5           -0.859682         1.747804          -0.785539    -0.694622
..                ...              ...                ...          ...
338          0.587066        -1.758454           0.926035     0.889551
340          0.513813        -1.453562           0.997351     0.796365
341          1.173091        -0.742147           1.496560     1.914605
342          0.220801        -1.199486           0.783404     1.231236
343          1.081525        -0.538886           0.854720     1.479734

[334 rows x 4 columns]

SciPy comes with `scipy.stats.zscore` that does the same. By default, it does not apply Bessel's correction, but we can enable that with `ddof=1`. We can apply the function to the entire column with `apply`. If the dataframe contained nonnumerical columns, we might want to choose those columns first.

In [7]:
from scipy.stats import zscore
df[numeric_columns].apply(zscore,ddof=1)

     culmen_length_mm  culmen_depth_mm  flipper_length_mm  body_mass_g
0           -0.896308         0.782313          -1.427380    -0.570373
1           -0.823055         0.121713          -1.070802    -0.508249
2           -0.676549         0.426605          -0.428961    -1.191618
4           -1.335827         1.087205          -0.571592    -0.943120
5           -0.859682         1.747804          -0.785539    -0.694622
..                ...              ...                ...          ...
338          0.587066        -1.758454           0.926035     0.889551
340          0.513813        -1.453562           0.997351     0.796365
341          1.173091        -0.742147           1.496560     1.914605
342          0.220801        -1.199486           0.783404     1.231236
343          1.081525        -0.538886           0.854720     1.479734

[334 rows x 4 columns]

Scikit-learn comes with `StandardScaler` that also does the same, but Bessel's correction is not used. This is inconsequential if *n* is large.

In [9]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit_transform(df[numeric_columns].to_numpy())

array([[-0.89765322,  0.78348666, -1.42952144, -0.57122888],
       [-0.82429023,  0.12189602, -1.07240838, -0.50901123],
       [-0.67756427,  0.42724555, -0.42960487, -1.19340546],
       ...,
       [ 1.17485108, -0.74326098,  1.49880565,  1.91747742],
       [ 0.22113229, -1.20128527,  0.78457953,  1.23308319],
       [ 1.08314735, -0.53969463,  0.85600214,  1.48195382]])

Standard scaler is particularly useful if we need to apply the same transformation to other datapoints (e.g., a separate test set). We want to use the same scale we determined with the training set. Calling `fit` or `fit_transform` will store the mean and standard deviation in the model. Future calls to `transform` (*without* `fit`) will then use the same values.